// <auto-generated />
using System;
using CatchSmartHeadHunter.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatchSmartHeadHunter.Migrations
{
    [DbContext(typeof(HhDbContext))]
    [Migration("20221010224531_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("CatchSmartHeadHunter.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.CandidatePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("PositionId");

                    b.ToTable("CandidatePositions");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.CompanyPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PositionId");

                    b.ToTable("CompanyPositions");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.ReqSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requirement")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("ReqSkills");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.CandidatePosition", b =>
                {
                    b.HasOne("CatchSmartHeadHunter.Candidate", null)
                        .WithMany("AppliedPositions")
                        .HasForeignKey("CandidateId");

                    b.HasOne("CatchSmartHeadHunter.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.CompanyPosition", b =>
                {
                    b.HasOne("CatchSmartHeadHunter.Company", null)
                        .WithMany("OpenPositions")
                        .HasForeignKey("CompanyId");

                    b.HasOne("CatchSmartHeadHunter.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.ReqSkill", b =>
                {
                    b.HasOne("CatchSmartHeadHunter.Position", null)
                        .WithMany("RequiredSkills")
                        .HasForeignKey("PositionId");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.Skill", b =>
                {
                    b.HasOne("CatchSmartHeadHunter.Candidate", null)
                        .WithMany("Skills")
                        .HasForeignKey("CandidateId");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.Candidate", b =>
                {
                    b.Navigation("AppliedPositions");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.Company", b =>
                {
                    b.Navigation("OpenPositions");
                });

            modelBuilder.Entity("CatchSmartHeadHunter.Position", b =>
                {
                    b.Navigation("RequiredSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
